- template_type: "button"
  text:
  buttons:
    - title:
      type:
      webview_height_ratio:
      url:
      fallback_url:
      payload:
        intent: 
        custom_data:
- template_type: "button"
  text:
  buttons:
    - title:
      type:
      webview_height_ratio:
      url:
      fallback_url:
      payload:
        intent: 
        custom_data: