- template_type: "generic" 
  elements:
    - title:
      url:
      subtitle:
      image_url:
      buttons:
        - title:
          type:
          webview_height_ratio:
          url:
          fallback_url:
          payload:
            intent: 
            payload_data: